services:
  - type: web
    name: real-house
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python seed_properties.py && uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DATABASE_URL
        fromDatabase:
          name: real-house-db
          property: connectionString

databases:
  - name: real-house-db
    databaseName: realhouse
    user: realhouse
